#+title: flowtrend: automatic gating of flow cytometry data using trend filtering


This directory contains code that directly generates a software package called
~flowtrend~, using [[https://github.com/jacobbien/litr-project][litr]]. Each R Markdown document in this directory -- called
~1description.Rmd~, ~2generate-data.Rmd~, and so forth -- contain code that
directly builds the R package.

* For package users

The official package website is [[https://sangwon-hyun.org/flowtrend-project/][here]]; go directly here to get started.

* For developers

The resulting "knitted" bookdown that defines the package can be found [[https://sangwon-hyun.org/flowtrend-project/create/][here]].

The resulting R package is in the subdirectory [[./flowtrend]], and can be
installed as follows.

#+begin_src R
remotes::install_github("sangwon-hyun/flowtrend-project", subdir = "flowtrend")
#+end_src

(Note, you should install the standalone R package ~/FlowTF_0.1.0.tar.gz~, using
~install.packages("FlowTF_0.1.0.tar.gz", repos=NULL, type="source")~, prior to
this package. This package contains one function written in Rcpp that is
required. )


Lastly, the code that replicates the numerical experiments in the paper can be found in
the subdirectory [[./inst]], currently placed on zenodo under DOI: ~10.5281/zenodo.16352652~.
